apiVersion: v1
kind: Pod
metadata:
  name: myfirstpod
  labels:
    app: myflaskapp
spec:
  containers:
    - name: myfirstpod
      image: psrv3/configmapexample
      ports:
        - containerPort: 5001
      envFrom:
        - configMapRef:
            name: my-flask-config