apiVersion: v1
kind: Pod
metadata:
  name: myfirstpodwithsec
  labels:
    app: myflaskapp
spec:
  containers:
    - name: myfirstpod
      image: psrv3/configmapexample
      ports:
        - containerPort: 5001
      env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: db-user-pass
              key: username